services:
  - type: web
    name: aivision-extract
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 500 --threads 4"
    autoDeploy: true
